apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: bluegreendeployments.demo.google.com
spec:
  group: demo.google.com
  version: v1
  scope: Namespaced
  names:
    plural: bluegreendeployments
    kind: BlueGreenDeployment
    shortNames:
    - bgd
